sudo: false

language: generic

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - llvm

cache:
  directories:
    - $HOME/.stack
    - $HOME/.local/bin
    - .stack-work/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm; fi
  - llvm-link --version
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [ `uname` = "Darwin" ]
    then
      travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - stack install happy alex

script:
  - stack setup
  - stack build
  - stack install cabal-install
  - stack exec -- cabal update
  - stack test --no-run-tests
  - stack build && (cd packages/lhc-prim/; stack exec -- cabal install --haskell-suite -w `stack exec -- which lhc`)
  - stack test
  - stack clean
