resolver: lts-12.26

allow-newer: true

packages:
- '.'
- bedrock
- haskell-crux
- libffi

- location:
    git: https://github.com/haskell-suite/haskell-tc.git
    commit: e47d66ceef3c737611c94ba8987c2b90c0244078
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-scope.git
    commit: 6f0082be2d906927372c1279e730dcf04a0765fc
  extra-dep: true

- location:
    git: https://github.com/haskell/cabal.git
    commit: b58b315835895b6c03311bc604f901f0939df02e
  subdirs:
    - cabal-install
    - Cabal
  extra-dep: true

- location:
    git: https://github.com/Lemmih/llvm-hs-pretty.git
    commit: 7e0ccd633195797e946699c4dbf8b1c741487c6e
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-packages.git
    commit: 9131a0b737e352393e94351dd63c495f2e9ff3e6
  extra-dep: true


extra-deps:
- haskell-src-exts-1.21.0
- llvm-hs-pure-6.0.0
- cabal-helper-0.7.3.0
- hse-cpp-0.2
- serialise-0.2.1.0
