resolver: lts-10.10

allow-newer: true

packages:
- '.'
- bedrock

- location:
    git: https://github.com/haskell-suite/haskell-tc.git
    commit: ee65a55e5e054b4e02ba2fe227240d21aa13cbd9
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-scope.git
    commit: 5d77593110a0455745da4f376a5bcdb9e511784c
  extra-dep: true

- location:
    git: https://github.com/Lemmih/cabal.git
    commit: 2bc6de8dec645e5b1425300078a3f81703ec3511
  subdirs:
    - cabal-install
    - Cabal
  extra-dep: true

- location:
    git: https://github.com/Lemmih/llvm-hs-pretty.git
    commit: 7e0ccd633195797e946699c4dbf8b1c741487c6e
  extra-dep: true


extra-deps:
- haskell-src-exts-1.20.2
- haskell-packages-0.6.1
- llvm-hs-pure-6.0.0
- resolv-0.1.1.1
- cabal-helper-0.7.3.0

flags:
  llvm-hs:
    shared-llvm: true
