resolver: lts-10.10

allow-newer: true

packages:
- '.'
- bedrock
# - ../haskell-crux

- location:
    git: https://github.com/haskell-suite/haskell-tc.git
    commit: a411e72a2dcabc7cf23cfb79f8801c4d2b102674
  extra-dep: true

- location:
    git: https://github.com/Lemmih/haskell-crux
    commit: b9366eec7860977a14c412bf6f0b3e4abbf66ebe
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-scope.git
    commit: e552d0ec70d473e4b4e2ac283cb21c4d8116766c
  extra-dep: true

- location:
    git: https://github.com/haskell/cabal.git
    commit: b58b315835895b6c03311bc604f901f0939df02e
  subdirs:
    - cabal-install
    - Cabal
  extra-dep: true

- location:
    git: https://github.com/Lemmih/llvm-hs-pretty.git
    commit: 7e0ccd633195797e946699c4dbf8b1c741487c6e
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-packages.git
    commit: 9131a0b737e352393e94351dd63c495f2e9ff3e6
  extra-dep: true


extra-deps:
- haskell-src-exts-1.20.2
- llvm-hs-pure-6.0.0
- resolv-0.1.1.1
- cabal-helper-0.7.3.0

flags:
  llvm-hs:
    shared-llvm: true
