resolver: lts-12.26

allow-newer: true

packages:
- '.'

- location:
    git: https://github.com/haskell-suite/haskell-tc.git
    commit: a411e72a2dcabc7cf23cfb79f8801c4d2b102674
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-scope.git
    commit: 6a149be78c62248ca4b76fc5279b55c01d548010
  extra-dep: true

extra-deps:
- haskell-src-exts-1.21.0
- serialise-0.2.1.0
