resolver: lts-12.26

allow-newer: true

packages:
- '.'

- location:
    git: https://github.com/haskell-suite/haskell-tc.git
    commit: e47d66ceef3c737611c94ba8987c2b90c0244078
  extra-dep: true

- location:
    git: https://github.com/haskell-suite/haskell-scope.git
    commit: 6f0082be2d906927372c1279e730dcf04a0765fc
  extra-dep: true

extra-deps:
- haskell-src-exts-1.21.0
- serialise-0.2.1.0
